name: Lint debug

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
  workflow_dispatch:

jobs:
  lint:
    name: Linting debug variant
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Create local.properties
        run: |
          echo "Creating local.properties in $(pwd)"
          echo "sdk.dir=$ANDROID_HOME" > local.properties # Or $ANDROID_SDK_ROOT, setup-java should provide one
          echo "VK_ID_REDIRECT_HOST=${{ secrets.VK_ID_REDIRECT_HOST_SECRET }}" >> local.properties
          echo "VK_ID_REDIRECT_SCHEME=${{ secrets.VK_ID_REDIRECT_SCHEME_SECRET }}" >> local.properties
          echo "VK_ID_CLIENT_ID=${{ secrets.VK_ID_CLIENT_ID }}" >> local.properties
          echo "VK_ID_CLIENT_SECRET=${{ secrets.VK_ID_CLIENT_SECRET }}" >> local.properties

      - name: Create google-services.json
        run: echo "${{ secrets.GOOGLE_SERVICES_JSON }}" > app/google-services.json

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Execute Gradle Command - lintDebug
        run: ./gradlew lintDebug